---
- hosts: validation
  vars:
    project_path: /opt/analytics/Mentoring-Analytics
  tasks:
    - name: Slurp hosts file
      slurp:
        src: "/opt/token/.token"
      register: slurpfile
    - name: Run vault credentials
      shell: "curl --location --request GET '{{ vaultAddress }}v1/elevate/mentored-portal' --header 'X-Vault-Token: {{ slurpfile['content'] | b64decode }}' | jq '.data' > '{{ project_path }}/data2.json'"
      register: vaultCurl
    - name: Change directory
      shell: cd {{project_path}}
    - name: Generate config.ini file
      shell: python deployment/lib/create_config.py
    - name: pull latest code
      git:
        repo: https://github.com/ELEVATE-Project/mentoring-analytics.git
        dest: "{{ project_path }}"
        version: "{{ gitBranch }}"
        force: yes
    - name: Create virtual Environment
      shell: python -m venv ../spark_env
    - name: Activate virtual environment
      shell: activate ../spark_env/bin/activate
    - name: Install requirements
      shell: pip install -r requirement.txt
    - name: Job execution
      shell: ./run.sh
    